<?php
//; 管理者|主担|モデレータ|一般|ゲスト
define('AUTHORITY_MYROOM_USE_FLAG', "1|1|1|1|0");
define('AUTHORITY_ALLOW_HTMLTAG_FLAG', "1|0|0|0|0");
define('AUTHORITY_ALLOW_LAYOUT_FLAG', "1|1|0|0|0");
define('AUTHORITY_ALLOW_ATTACHMENT', "2|2|2|1|0");
define('AUTHORITY_ALLOW_VIDEO', "1|0|0|0|0");
define('AUTHORITY_MAX_SIZE', "8|4|3|1|1");
define('AUTHORITY_MAX_SIZE_LIST', "5242880|10485760|20971520|52428800|104857600|209715200|524288000|1073741824");
define('AUTHORITY_MAX_SIZE_LIST_DEFAULT', "8|4|3|1|1");
define('AUTHORITY_PUBLIC_CREATEROOM_FLAG', "1|0|0|0|0");
define('AUTHORITY_GROUP_CREATEROOM_FLAG', "1|0|0|0|0");

define('AUTHORITY_MYROOM_USE_FLAG_DISABLED', "0|0|0|0|0");
define('AUTHORITY_ALLOW_HTMLTAG_FLAG_DISABLED', "1|0|0|1|1");
define('AUTHORITY_ALLOW_LAYOUT_FLAG_DISABLED', "1|0|0|0|0");
define('AUTHORITY_ALLOW_ATTACHMENT_DISABLED', "1|0|0|0|1");
define('AUTHORITY_ALLOW_VIDEO_DISABLED', "1|0|0|0|1");

//define('AUTHORITY_MAX_SIZE_DISABLED', "0|0|0|0|1");
define('AUTHORITY_PUBLIC_CREATEROOM_FLAG_DISABLED', "0|0|0|0|0");
define('AUTHORITY_GROUP_CREATEROOM_FLAG_DISABLED', "0|0|0|0|0");

//; white_list
define('AUTHORITY_SYS_DEFAULT_MODULES_SYSADMIN', "all");
define('AUTHORITY_SYS_DEFAULT_MODULES_ADMIN', "userinf|user|room|backup|holiday");
define('AUTHORITY_SYS_DEFAULT_MODULES_CHIEF', "userinf|user|room|backup");
define('AUTHORITY_SYS_DEFAULT_MODULES_MODERATE', "userinf|user|room|backup");
define('AUTHORITY_SYS_DEFAULT_MODULES_GENERAL', "userinf|user");
define('AUTHORITY_SYS_DEFAULT_MODULES_GUEST', "userinf|user");

//;white_list
define('AUTHORITY_SYS_DISABLED_MODULES_SYSADMIN', "");
define('AUTHORITY_SYS_DISABLED_MODULES_ADMIN', "all");
define('AUTHORITY_SYS_DISABLED_MODULES_CHIEF', "userinf|user|room|backup|holiday");
define('AUTHORITY_SYS_DISABLED_MODULES_MODERATE', "userinf|user|room|backup|holiday");
define('AUTHORITY_SYS_DISABLED_MODULES_GENERAL', "userinf|user|room|backup");
define('AUTHORITY_SYS_DISABLED_MODULES_GUEST', "userinf|user|room|backup");

define('AUTHORITY_DEFAULT_LEVEL', "50");
?>